### ISSUE TITLE
Generate the Prediction Label in the Right Format for the Challenge Server

### ISSUE THREAD

**Issue by sunformoon** [yulequan/HeartSeg#2]
Hi Lequan,

Thank you for your nice work! Can you share the code to generate the prediction label in the right format (maybe nii?) that can be directly evaluated by the challenge server?

I evaluated the DICE on the training set by comparing the predicted and given the label in ".mat" format, which seemed reasonable. Then, I tried to generate the NII format from ".mat" using the make_nii function in the NIfTI toolbox. And upload it to the challenge testing server, it always output -inf.

I would really appreciate it!

Best,
Zhuotun

**Comment by yulequan** [comment]
Hi Zhuotun,

You can refer the following code:

 %% save with original header info.
 img_src = load_untouch_nii(vol_path);
 vote_label = permute(vote_label, [2 3 1]);
 vote_label = rot90(vote_label, 2);      
 img_src.img = uint16(vote_label);
 save_name = "";
 save_untouch_nii(img_src, save_name);
