### ISSUE TITLE
Padding the Segmentation

### ISSUE THREAD

**Issue by sunformoon** [yulequan/HeartSeg#4]
Hello Lequan,

I am curious about a padding operation here: https://github.com/yulequan/HeartSeg/blob/b689b376d9cce9e02adf33606035892284c8814c/code/util/Create_ROIs.m#L28

If my understanding is correct, you pad the ROI if the size is smaller than the crop size. Why would you pad the segmentation ground truth to be 100? Should we pad it as 0s as the background truth label or is 100 a flag of padding?

Thank you~ :)

Best,
Zhuotun

**Comment by yulequan** [comment]
Hi Zhuotun,

This is following the idea in deeplab. 100 is a flag of padding and we will remove these voxels(samples) when calculating the loss.  In the softmaxloss layer, we can add "ignore_label" in the parameter. I remove the usage in the provided prototxt file. You can refer the following code:

https://github.com/yulequan/3D-Caffe/blob/4bdc9bedf4f306ed6e4e41c3c7587952ec0363e4/src/caffe/layers/softmax_loss_layer.cpp#L23

**Comment by sunformoon** [comment]
Hello Lequan,

I see. Thank you a lot for your clarification! I was not aware of that in the beginning. :)

Best,
Zhuotun
