### ISSUE TITLE
"caffe.TransformationParameter" has no field named "crop_size_l"

### ISSUE THREAD

**Issue by debinz** [yulequan/HeartSeg#5]
Hi there,
when I try to run start_train.sh in DenseVoxNet, I run to an error and I don't know how to solve it. I've searched but I could not find any solution.
Here is error:

![screenshot from 2017-12-02 18-35-35](https://user-images.githubusercontent.com/24296206/33514484-ad5aabd8-d78f-11e7-86f7-9d16877e090d.png)

thanks regards.

**Comment by yulequan** [comment]
Did you use the 3D version Caffe as the installation?

**Comment by debinz** [comment]
@yulequan yeah, I built the wrong branch, after use git checkout 3D-Caffe to switch the correct branch, the problem is gone. thanks a lot!
